<a href="https://colab.research.google.com/github/YuliaLoburets/ML_learning/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [ ]:
import numpy as np
vector = np.random.rand(1,10)
print(vector)

[[0.82033331 0.19156365 0.32279034 0.06039655 0.11971088 0.5756563
  0.4217266  0.73385636 0.25605861 0.83868838]]


In [ ]:
A = np.array([[11,14,17],
          [20,23,26],
          [29,32,35]])
print(A)

[[11 14 17]
 [20 23 26]
 [29 32 35]]



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [ ]:
vector = vector.round(2)+10
print(vector)


[[10.82 10.19 10.32 10.06 10.12 10.58 10.42 10.73 10.26 10.84]]


In [ ]:
np.dot(A, 2)

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [ ]:
new_vector = vector**2
print(new_vector)

[[117.0724 103.8361 106.5024 101.2036 102.4144 111.9364 108.5764 115.1329
  105.2676 117.5056]]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [ ]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [ ]:
result_matrix = np.dot(B,A)
print(result_matrix)

[[0.7281 0.5202]
 [0.2034 0.2846]]


In [ ]:
new_matrix = np.dot(result_matrix, C)
print(new_matrix)

[[0.5202]
 [0.2846]]


In [ ]:
new_matrix_2 = np.dot(result_matrix, D)
print(new_matrix_2)

[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [ ]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [ ]:
vector_T = vector.T
print(vector_T)

[[10.82]
 [10.19]
 [10.32]
 [10.06]
 [10.12]
 [10.58]
 [10.42]
 [10.73]
 [10.26]
 [10.84]]


Вектор транспонувався - був один рядок з 10 колонками, а став з однією колонкою та 10 рядками.

In [ ]:
column_vector = np.expand_dims(vector,axis=1)
print(column_vector)

[[[10.82 10.19 10.32 10.06 10.12 10.58 10.42 10.73 10.26 10.84]]]


In [ ]:
column_vector.shape

(1, 1, 10)

In [ ]:
column_vector_2 = np.expand_dims(vector_T,axis=1)
print(column_vector_2)

[[[10.82]]

 [[10.19]]

 [[10.32]]

 [[10.06]]

 [[10.12]]

 [[10.58]]

 [[10.42]]

 [[10.73]]

 [[10.26]]

 [[10.84]]]


In [ ]:
column_vector_2.shape

(10, 1, 1)

Застосувала цей метод до оригінального вектора та до транспонованого, в обох випадках, бачимо, що додалась розмірність. В першому випадку одна матриця в стосі, один рядок, 10 елементів в рядку , в іншому випадку - 10 матриць в стосі, по одному рядку , по одному елементу в кожному рядку.

In [ ]:
column_vector_transp = column_vector.T
print(column_vector_transp)

[[[10.82]]

 [[10.19]]

 [[10.32]]

 [[10.06]]

 [[10.12]]

 [[10.58]]

 [[10.42]]

 [[10.73]]

 [[10.26]]

 [[10.84]]]


In [ ]:
column_vector_transp.shape

(10, 1, 1)

In [ ]:
column_vector_2_transp = column_vector_2.T
print(column_vector_2_transp)

[[[10.82 10.19 10.32 10.06 10.12 10.58 10.42 10.73 10.26 10.84]]]


In [ ]:
column_vector_2_transp.shape

(1, 1, 10)

Коли зробили транспонування вектора column_vector, то він змінив розмірність з (1,1,10) на розмірність (10,1,1). А column_vector_2 після транспонування змінив розмірність на (1,1,10).